### ISSUE TITLE
 Liberal filter bias 

### ISSUE THREAD

**Issue by eyesonlyhack** [selfagency/bs-detector#12]
If you lookup some those websites on wikipedia, certain sites are clearly not BS. They are either libertarian, conservative, Christian, far-right or alt-right. For example, Prisonplanet does cover some conspiracy theories but does this make the whole site BS when I found most articles to be perfectly reasonable and newsworthy? 

RT has a Russian Putin bias but most media outlets are very bias towards the Democratic Party or certain candidates in the US, like a bias towards Hillary Clinton, Obama or the Democratic party. So it is a bit of a double standard to include RT. 

I will not go through the whole list but from the top of my head these sites should not be on the list:
breitbart.com
rt.com
prisonplanet.com
prisonplanet.tv
twitchy.com
wnd.com

Maybe you should categorise websites as alt-right, christian, Democrat bias, fake, satire, conservative, liberal, etc. and let people decide what to filter? As the plugin stands now, you should rename the plugin to liberal-bias-bs-detector or something.

**Comment by selfagency** [comment]
If you think WorldNetDaily and PrisonPlanet are legitimate news sources, we have nothing to discuss.

**Comment by Justin-Chaschowy** [comment]
Lmao

>We have nothing to discuss.

What a pompous ass.

**Comment by selfagency** [comment]
That makes two violations of our [code of conduct](https://github.com/selfagency/bs-detector/blob/master/CODE_OF_CONDUCT.md). Bye, now!
