### ISSUE TITLE
Please add http://aneurotickid.topratedviral.com/

### ISSUE THREAD

**Issue by tresrottn** [selfagency/bs-detector#16]
Please add http://aneurotickid.topratedviral.com/ to the list. 
Questionable content http://aneurotickid.topratedviral.com/article/donald-trump-legalize-marijuana-in-all-50-states/promote/1001241

Trump never said this. It's already hit the Snopes group on Facebook as folks look for confirmation if it's true or not.
Thanks for the addon, it's working quite flawlessly, and I have no problem recommending it to my friends and the new folks to the snopes page.

**Comment by selfagency** [comment]
added
