### ISSUE TITLE
Link Shorteners

### ISSUE THREAD

**Issue by agucova** [selfagency/bs-detector#17]
The extension doesn't seem to detect articles that are behind a link shortener like bit.ly or goo.gl.

By example, Twitter uses t.co for all links, making the extension unusable.

<img width="586" alt="notworking" src="https://cloud.githubusercontent.com/assets/4694408/20463827/a32a15e8-af1a-11e6-9784-d13233432ec8.png">

**Comment by agucova** [comment]
It seems the extension filters for facebook.com, but the problem persists with facebook articles using link shorteners, like [The Onion](https://www.facebook.com/TheOnion/).

**Comment by selfagency** [comment]
Yes, I am aware of the issue. I'm not really sure how to address it tho. It would require some sort of link resolver, I imagine.

**Comment by selfagency** [comment]
something like this maybe

```
    function traceUrl($url, $hops = 0)
    {
        if ($hops == MAX_URL_HOPS)
        {
            throw new Exception('TOO_MANY_HOPS');
        }

        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_HEADER, 1);
        curl_setopt($ch, CURLOPT_NOBODY, 1);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        $r = curl_exec($ch);

        if (preg_match('/Location: (?P<url>.*)/i', $r, $match))
        {
            return traceUrl($match['url'], $hops + 1);
        }

        return rtrim($url);
    }
```

**Comment by selfagency** [comment]
this has been addressed in the latest update.
