### ISSUE TITLE
Websites to assess

### ISSUE THREAD

**Issue by jprobst24** [selfagency/bs-detector#19]
westernjournalism.com
redstatewatcher.com
thehill.com
sofrep.com
It would also be great if there was a way for users to submit additional websites for assessment.

**Comment by selfagency** [comment]
i've added the first two as extremely biased sources. the second two seem pretty legitimate. unless you can point to numerous examples of the purposeful misleading of readers, they don't meet the criteria. you can add to the list by editing the json file in the chrome/data folder and submitting a pull request. eventually, i will add a feature for people to submit sites through the plugin itself.
