### ISSUE TITLE
The Australian Newspaper http://www.theaustralian.com.au/ For BS detector

### ISSUE THREAD

**Issue by auswegian** [selfagency/bs-detector#20]
Unreliable news source, for the BS detector.
Murdoch media site,http://www.theaustralian.com.au/
Promoting alt right propaganda, akin to Fox News.

**Comment by selfagency** [comment]
sorry, but as much as i despise murdoch's agenda, we're not including legitimate newspapers in this list.

**Comment by auswegian** [comment]
A shame, it would appear that the mainstream media is the most important
ones to call out for misinformation, propaganda and outright lies, being
that so many form their opinions upon what they read and hear via these
channels
