### ISSUE TITLE
Please consider removing Private-Eye.co.uk

### ISSUE THREAD

**Issue by mtoner** [selfagency/bs-detector#22]
Please consider removing Private-Eye.co.uk from the list. 

Here is an article about Private Eye and its editor Ian Hislop:
http://www.telegraph.co.uk/culture/9692766/Inside-the-Private-world-of-Ian-Hislop.html

Fittingly, here it is arguing against Facebook allowing autism "cure" articles:
http://www.private-eye.co.uk/issue-1431/in-the-back

It is left leaning, mostly offline magazine (the UK's No.1 best-selling news and current affairs magazine) with satirical covers but has covered very important topics and investigations.

Keep up the great work.

**Comment by selfagency** [comment]
it will be gone in the next update
