### ISSUE TITLE
Chrome extension: scrolling in OS X using touchpad lagging

### ISSUE THREAD

**Issue by thisiskatkat** [selfagency/bs-detector#24]
Great work!

The Chrome extension seems to have some performance issues.
After installing this, scrolling through websites using touchpad is visibly slower.
Tried in Chrome, OS X. Examples of websites tested - facebook.com, http://www.theonion.com/, breitbart.com

Let me know if you need more info/testing etc.

**Comment by selfagency** [comment]
an update was pushed that should have resolved all scrolling issues. make sure to update and reload the extensions in your browser.

**Comment by thisiskatkat** [comment]
I see, no more
```
$(window).scroll(function() {		
 	linkWarning();		
 });
```
:)
