### ISSUE TITLE
Facebook solution flags whole post versus individual links

### ISSUE THREAD

**Issue by spryde** [selfagency/bs-detector#27]
Changes for facebook are awesome but the whole post is flagged as BS if one of the comments contains a flagged site. Attached image has a naturalnews.com link in a comment but the top post is flagged. Maybe misleading to some. 

![image](https://cloud.githubusercontent.com/assets/3370981/20536013/5426a398-b0b5-11e6-809a-12620f22aa42.png)

**Comment by Deelite310** [comment]
there is no comments, but its "flagging" an anime blog site as "State news Source" - via facebook

![2016-11-22_113130](https://cloud.githubusercontent.com/assets/2086137/20538662/030daeb0-b0a7-11e6-89b3-dec4efacf96e.png)

**Comment by Deelite310** [comment]
another one. A personal artist website, is being flagged as a State News source. Comments to the post contain no links - via facebook

![2016-11-22_113530](https://cloud.githubusercontent.com/assets/2086137/20538780/7ccaec86-b0a7-11e6-9d2d-91b36a8c0164.png)

**Comment by Deelite310** [comment]
my issue from yesterday was closed, yet caught in the notices


![2016-11-22_114025](https://cloud.githubusercontent.com/assets/2086137/20538985/5128fcb6-b0a8-11e6-8270-2d9b6ea55f13.png)

**Comment by selfagency** [comment]
thanks-- i see what's wrong and will work on a fix.

**Comment by spryde** [comment]
Yeah, I was about to suggest on inject.js to change 

`theWrapper = $(this).closest('div.userContentWrapper'); `

to 

`theWrapper = $(this).closest('div.UFIComment');`

which results in 

![image](https://cloud.githubusercontent.com/assets/3370981/20539335/ac8fd31c-b0c2-11e6-9b79-92d0087b80e4.png)

That fixes my reported issue.

**Comment by selfagency** [comment]
a fix will be issued shortly
