### ISSUE TITLE
Pocket app (read later) false positive

### ISSUE THREAD

**Issue by rzombeck** [selfagency/bs-detector#28]
Nearly all the links that are saved in the Pocket app show as questionable website. The used is not a direct link, but a link that redirects to the saved article.

![2016-11-22_21-32-31](https://cloud.githubusercontent.com/assets/5642489/20549562/872d74e2-b0fb-11e6-9f58-55b396935068.jpg)
![2016-11-22_21-31-53](https://cloud.githubusercontent.com/assets/5642489/20549563/872d9328-b0fb-11e6-9a62-00d2a7879402.jpg)

**Comment by selfagency** [comment]
thanks for pointing this out, i will work on it.

**Comment by selfagency** [comment]
i'm unable to replicate this issue using my pocket account. could you right click on the link, click inspect element, hit escape when the inspector palette opens, and send me a screenshot?

**Comment by rzombeck** [comment]
Oddly enough, I am also unable to recreate the issue. In fact, I'm no longer seeing the warnings as I scroll facebook or other sites for that matter. I'm trying to determine if it's a local problem. Is the plugin dependent on anything in particular? Not sure you still want to screenshot, but it's attached.
![2016-11-23_16-46-16](https://cloud.githubusercontent.com/assets/5642489/20579723/6e19358a-b19c-11e6-9599-603435967c77.jpg)

**Comment by selfagency** [comment]
i mean, it's possible it's conflicting with another plugin, but this extension only has one external dependency, which is jquery. can you check what it says in the console? i see 20 errors. (the red dot at the top right of your screenshot). can you click on the console tab and show me what it says there?

**Comment by rzombeck** [comment]
![2016-11-23_17-31-07](https://cloud.githubusercontent.com/assets/5642489/20580816/b554c9fe-b1a2-11e6-9ff9-47b4eead6a41.jpg)

**Comment by selfagency** [comment]
looks like the url expander api i was using went offline and is breaking the plugin. i just issued a fix.

**Comment by rzombeck** [comment]
Cool. The issue has returned in Pocket unfortunately. Here's the screenshot of the error.

![2016-11-23_23-17-01](https://cloud.githubusercontent.com/assets/5642489/20586556/0c1ae450-b1d3-11e6-851e-05aa3d1f9a19.jpg)

Personally, it's not a problem for me.

Also. Try going to infowars facebook page. The warning shows up on links in which the URL is pasted into the post, but not the other.

![2016-11-23_23-19-53](https://cloud.githubusercontent.com/assets/5642489/20586602/772ce3f6-b1d3-11e6-8291-503311327cc9.jpg)

Have a happy thanksgiving.
:-)

**Comment by selfagency** [comment]
just pushed an update. v0.1.6. update your extensions and let me know if it's resolved for you.

**Comment by selfagency** [comment]
Appears to be resolved.
