### ISSUE TITLE
Suggestions for improving performance

### ISSUE THREAD

**Issue by benbuckman** [selfagency/bs-detector#3]
First of all, thank you for making this.

Looking at the code, it appears that it scans all links on the page [every 10ms](https://github.com/selfagency/bs-detector/blob/master/ext/src/inject/inject.js#L397), on every page. (Is that accurate?) That seems like it could slow down the browser (and increase CPU usage) significantly.

Suggestions for improving performance:

1. Limit it to specific domains, like facebook.com? (perhaps user-configurable)
2. Rather than checking every 10ms, check on relevant events, like page load or scroll.
3. Not use jQuery (for example, use `document.querySelectorAll` instead), it's a lot of bloat to add to every single page.

Thank you!

**Comment by selfagency** [comment]
These are good suggestions. However, it's not checking every 10ms, it is checking on page load and scroll only. I will definitely take 1 and 3 under advisement.

**Comment by benbuckman** [comment]
Thanks!
Is the 10ms interval simply waiting for the page to load?

**Comment by selfagency** [comment]
Yeah, it's `$(document).ready()`.

**Comment by EoinGriffin-AI** [comment]
Since there's already an issue started re:performance I'll add in my suggestion here.
I see you're currently using the scroll event, but that's slowing down my browser significantly (I might try this extension again if the performance improves).
To get the maximum performance I recommend using a MutationObserver so that it will only check the DOM when it changes (an anchor tag is added or updated, for example).

Here's a quick example of how that would work (sorry, I don't have much time for raising a pull request here)
```
var mutationObserver = new MutationObserver(function() {
    //check the list
});

var contentAreaSelector = '#contentArea'; // If needed, modify this selector to also include FB ads at the side of the page, or any other areas worth checking.
var mutationObserverConfig = {childList: true, subtree: true}; // This ought to be enough
mutationObserver.observe($(contentAreaSelector), mutationObserverConfig );
```

**Comment by selfagency** [comment]
@EoinGriffin-AI Thanks, I will take a look into that and try to integrate it in the next significant update.

**Comment by Bastlynn** [comment]
I didn't even know that was a feature in JS. Thank you!

**Comment by anodynos** [comment]
You can also place `var links = [...]` outside the `setInterval` function, to both clean the code and not redclare it at each run. 

You can add it on line 2 after `chrome.extension.sendMessage({}, function(response) {` or better wrap the whole code with a closure and stick it there, eg
```
(function(){
var links = [...]; 

chrome.extension.sendMessage({}, function(response) { ...}); 
 }())
```

**Comment by selfagency** [comment]
I've switched the jQuery Slim and implemented the mutation observer.
