### ISSUE TITLE
Merge to WebExtensions

### ISSUE THREAD

**Issue by Bastlynn** [selfagency/bs-detector#44]
@selfagency Given how alike the code between the two is, and that the WebExtensions the Firefox version uses are almost entirely compatible with chrome - we should take a look at merging the two versions into a single bit of code so we aren't supporting more code than we need to be.

Compatibility tables are here for WebExtension support cross browsers:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

**Comment by selfagency** [comment]
I support doing this, if you want to take a stab at it. But we should wait until we resolve the performance and shortlink issues first.

**Comment by IanDarwin** [comment]
At least the data/data.json file should be common! This copy-and-paste is already out of sync on master.

**Comment by selfagency** [comment]
complete! #111
