### ISSUE TITLE
Add highlighting of words or names of fake news influencers

### ISSUE THREAD

**Issue by neomodern** [selfagency/bs-detector#55]
The current list is suited for highlighting links on Facebook + on the site itself, an even more global fake news strategy could be highlighting when the names of fake news influencers are written online.

This could be achieved by simply merging in the existing [Nazi Detector](https://github.com/k0nsl/nazi-detector) extension which highlights names of Nazi sympathisers.

**Comment by neomodern** [comment]
Oh just realised that's your extension lol.

**Comment by neomodern** [comment]
This could be extended further: similar to Imagus, there could be a pop-up when you highlight these words which shows citations for the reason why it was highlighted.

**Comment by selfagency** [comment]
I'll add this to our 'possible new features' list.
