### ISSUE TITLE
idSite() not being triggered in 0.2.4 when loading unpacked extension

### ISSUE THREAD

**Issue by BigMcLargeHuge** [selfagency/bs-detector#56]
I'm running into an interesting issue when loading the unpacked extension in developer mode.  I'm running Ubuntu16.04; chrome Version 54.0.2840.100 (64-bit).  The big picture is that `idSite()`is not being called.  The reason seems to be that linkWarning() is running before idSite() runs on the initial load.  See below (note comments):

```
        function trigger(mutations) {
          if (arguments.length === 0) {
            mutationObserver.disconnect();
            linkWarning();
            // link warning sets firstLoad = false without siteId being set by idSite()
            mutationObserver.observe(targetNode, observerConfig);
            return;
          }
          var hasDesired = false, i = mutations.length, nodes, j;
          mutationObserver.disconnect();
          // asynch(expandLinks, linkWarning);
          // firstLoad is false and conditional doesn't fire
          if (firstLoad) {
            idSite();
            if (siteId === 'badlink') {
              flagSite();
            }
}
```

This seems to be resolved by moving the firstload conditional up above the initial call to linkWarning().  This doesn't seem to be an issue in the version that's currently in the app store under 0.2.4.  Thoughts?

**Comment by BigMcLargeHuge** [comment]
I've tentatively resolved this issue in my latest pull request #57 Still open to comments on the apparent bug.

**Comment by selfagency** [comment]
this is the firefox version, correct?

**Comment by BigMcLargeHuge** [comment]
Nope, chrome

**Comment by selfagency** [comment]
dev branch?

**Comment by BigMcLargeHuge** [comment]
I found the problem even when I downloaded [this zip](https://github.com/selfagency/bs-detector/releases/tag/v0.2.4) and loaded the chrome plugin as an unpacked extension.

**Comment by selfagency** [comment]
Ah. Well it's fixed now but I haven't pushed a new release because something else is broken now.

**Comment by BigMcLargeHuge** [comment]
Actually, I'm finding that it hasn't been fixed.  I just loaded downloaded the head and am finding the same problem.

**Comment by selfagency** [comment]
dev or master?

**Comment by BigMcLargeHuge** [comment]
Master branch

**Comment by selfagency** [comment]
check out dev, lots of changes
