### ISSUE TITLE
Facebook is now blocking links to the bs-detector

### ISSUE THREAD

**Issue by mtaylorcg** [selfagency/bs-detector#60]
Facebook now blocks any links or posts referencing the bs-detector.   They are reporting it as a malicious site and for "security purposes"  are blocking it.
![message1](https://cloud.githubusercontent.com/assets/131280/20837455/22b5f5f6-b872-11e6-9261-cf2028b844b2.JPG)
![message2](https://cloud.githubusercontent.com/assets/131280/20837460/24c2211c-b872-11e6-8dc7-e764e0a2298b.JPG)

**Comment by selfagency** [comment]
WHAAAAAT

**Comment by andylockran** [comment]
you're making the Zuck look bad..

**Comment by selfagency** [comment]
apparently so. streisand effect is gonna make 'em look WAAAAAY worse.

**Comment by selfagency** [comment]
http://motherboard.vice.com/read/an-interview-with-the-guy-whose-fake-news-plugin-was-just-blocked-by-facebook

https://www.inverse.com/article/24621-facebook-bs-detector

**Comment by selfagency** [comment]
This has been resolved thanks to the inqiuiries of the BBC, CBC, Buzzfeed, WSJ, the Guardian and others!
