### ISSUE TITLE
Consider adding 'clickbait' category

### ISSUE THREAD

**Issue by IanDarwin** [selfagency/bs-detector#74]
### Extension version
Any

### Browser and browser version
[ ] Chrome [ ] Firefox [ ] Other, Version:
Any

### OS and OS version
[ ] Mac [ ] Windows [ ] Linux, Version:
Any

### Actual behavior

There are many sites like "spin-news.com" which pretend to offer news on current topics but when you click on them you wind up in some advertising garbage, hence "clickbait" should be a category (hopefully reserved for sites that contain close to 0% actual content).

### Steps to reproduce behavior

Read Facebook long enough, you will see one of their ads :-)

**Comment by selfagency** [comment]
Agreed, it's a valuable distinction.
