### ISSUE TITLE
Unable to load unpacked dev branch

### ISSUE THREAD

**Issue by BigMcLargeHuge** [selfagency/bs-detector#77]
Hi All,

After the recent merges to the dev branch, I am confronted with the following error when I try to load the unpacked extension: 
>Failed to load extension from: ~/bs-detector/chrome
Could not load javascript 'js/jquery-3.1.1.slim.min.js' for content script.

Since the jquery file was recently moved to a shared directory in #67, is there a trick to taking advantage of this new configuration?

**Comment by selfagency** [comment]
you need to run the gulp task after you pull the branch and then after you make any changes to content in the _shared folder. tho i suppose we could add a watch task to do it automatically when changes are detected.
