### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by ZKnowN** [selfagency/bs-detector#9]
Any love for firefox users?

**Comment by Bastlynn** [comment]
The greasemonkey script got put up a few hours ago. I'm working on a proper FireFox extension later this week.

**Comment by selfagency** [comment]
@Bastlynn fyi, there have been some significant updates, some of which are dependent on the chrome api. if you can port it again, that'd be awesome.

**Comment by Bastlynn** [comment]
@selfagency  Updates are in on the latest pull request, along with the FireFox extension. :) Enjoy!

**Comment by selfagency** [comment]
@bastlynn Trying to upload to the Firefox Add-On Directory and getting an error:
![Screenshot 2016-11-29 11.44.20](http://static.gitscout.com/b0c9d1f71f1523cf4661aa8ce455a2bd9aee2d42d3a64076c180f9e66933ddfd.png)

Could you work on that?

Thanks!
