### ISSUE TITLE
Data property ordering/structuring

### ISSUE THREAD

**Issue by tomlutzenberger** [selfagency/bs-detector#91]
**Suggestions:**
- Move the language property to the begin of the line to make it easier to maintain (multi-selection in editors)
- Use whitespaces to add indentions between properties to make the file look more structured

**Comment by selfagency** [comment]
sounds good, as does the hash idea described on gitter

**Comment by tomlutzenberger** [comment]
Could be combined then. I'd suggest to **first change the data structure** and merge the EU data **afterwards**.

Is it necessary to order the data by url, language etc?

**Comment by selfagency** [comment]
we should order by language then url

**Comment by selfagency** [comment]
may as well merge the files first so you don't have to reformat two files

**Comment by tomlutzenberger** [comment]
Yes, you're right.

**Comment by tomlutzenberger** [comment]
Fixed in #95
