### ISSUE TITLE
You need better instructions for reporting links

### ISSUE THREAD

**Issue by BarkingUnicorn** [selfagency/bs-detector#97]
So I went to https://github.com/selfagency/bs-detector/issues/53 and found no clue what to do from there.  You may want to fix that.

Here's what I want to report:

http://countercurrentnews.com/2016/12/dapl-corporation-just-told-army-corp-will-want-keep-building-illegal-pipeline-standing-rock/

Headline:  DAPL Corporation Just Told The Army Corp They Will Do What They Want And Keep Building ILLEGAL Pipeline At Standing Rock

Truth:  Energy Transfer Partners (ETP, the "DAPL Corporation) issued a press release stating, "“as stated all along, ETP and SXL are fully committed to ensuring that this vital project is brought to completion and fully expect to complete construction of the pipeline without any additional rerouting in and around Lake Oahe. Nothing this Administration has done today changes that in any way.”

ETP did not do what this clickbait headline says.  Countercurrentnews.com spews this crap all day long. I'd love to see them on your list.

**STOP AND READ THIS**
If you want to report a link to add or remove from our dataset, go here: https://github.com/selfagency/bs-detector/issues/53
If you want to report performance issues, go here: https://github.com/selfagency/bs-detector/issues/50
Otherwise, delete this block and proceed to file an issue.
---

### Browser and browser version
[ ] Chrome [ ] Firefox [ ] Other, Version:

### OS and OS version
[ ] Mac [ ] Windows [ ] Linux, Version:

**Comment by selfagency** [comment]
thanks we'll review countercurrentnews
